### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/foundationcdn#1]
- Firefox is kinda broken (popups, dropdown, table)
- On Chrome copy buttons are broken
- When you enable "SRI", scripts must also auto-tick https://dl.dropboxusercontent.com/s/jd7r47rlvpjzfcq/2015-12-04_16-46-33.png?dl=0
- Make the version dropdown dynamic, it should load the versions from the JSON file
- Make the download link dynamic.
- "Our CDN features" must scroll down to the features section
- When using "Show more" it deselects all selected files

**Comment by MartinKolarik** [comment]
> On Chrome copy buttons are broken

All of them? What version and what OS? They work for me.

**Comment by jimaek** [comment]
There is no hover effect on Chrome. Windows 10, latest version

**Comment by MartinKolarik** [comment]
Oh ok, I thought you meant the copy functionality doesn't work.
