### ISSUE TITLE
SRI should be default

### ISSUE THREAD

**Issue by fulldecent** [jsdelivr/foundationcdn#9]
Check the box by default. Respect privacy.

**Comment by fulldecent** [comment]
To be clear, are you still accepting contributions to this project?? If so would a PR that fixes this be in scope to be merged?

**Comment by jimaek** [comment]
Hey, unfortunately this project is no longer maintained. You will see that foundationcdn.com redirects to jsDelivr.  It has SRI, download stats and much more.
I would consider bringing the dedicated site back if someone was willing to rewrite it to node.js and update the design.

**Comment by fulldecent** [comment]
Thanks for the response. Please consider to archive the repo.
